### ISSUE TITLE
Photo Gallery \ Фото галерея

### ISSUE THREAD

**Issue by DivanX10** [t0mer/deepstack-trainer#2]
**Thank you for the great component for deepstack. Can you add a photo gallery? It would be very convenient to know which photos were uploaded.**
Спасибо вам за отличный компонент для deepstack. Можете добавить фото галерею? Это было бы очень удобно, чтобы знать какие фотографии были загружены.

**Comment by t0mer** [comment]
Hi DivanX10,
At the moment i'm not saving the photos, the phoho you uploads wil be deleted once the procecss is completed.
Hope to add it to the next version.

**Comment by t0mer** [comment]
Done in version 1.0.0
Will display new images only.

**Comment by DivanX10** [comment]
Thank you for adding the gallery, it became just super. Tell me, is there a possibility, and is it even possible to add a photo deletion function to the gallery and edit the name of the photo?
