### ISSUE TITLE
Face Learning Teach Me button does nothing

### ISSUE THREAD

**Issue by ddbrown2** [t0mer/deepstack-trainer#4]
Running in docker on Unraid, just pulled the from docker hub with deepstack version "DeepStack: Version 2021.02.1"
following enabled
/v1/vision/face
---------------------------------------
/v1/vision/face/recognize
---------------------------------------
/v1/vision/face/register
---------------------------------------
/v1/vision/face/match
---------------------------------------
/v1/vision/face/list
---------------------------------------
/v1/vision/face/delete
---------------------------------------
/v1/vision/detection
---------------------------------------
/v1/vision/scene
---------------------------------------

I browse to an image
Type in a name
and click Teach me and get no response.  No error, but no response.
If I leave off the name I get an error stating I need a name

If I use Face Recognition 
browse to an image
Click who is it
I get  (Success) the person in the picture is No connection adapters were found for IP address:5000/v1/vision/facerecognize

I also get errors when using Object Detection and Scene Detection:
Error
No connection adapters were found for IP address:5000/v1/vision/detection   Although I do use BlueIris and it does detect objects.
Same error with Scene, but with  /v1/vision/scene

**Comment by ocsele** [comment]
Very same problem here.

Maybe it's worth mentioning that I'm running Deepstack through the native Windows 10 client, not via docker.
Docker-Trainer config for me is following:
`version: "3.7"
services:
  deepstack_trainer:
    image: techblog/deepstack-trainer
    container_name: deepstack_webui
    privileged: true
    restart: always
    environment:
      - DEEPSTACK_HOST_ADDRESS=192.168.0.15:90
      - DEEPSTACK_API_KEY=
      - MIN_CONFIDANCE=0.70
    ports:
      - "8501:8080" `
Upon trying to recognize a photo, I get the following popup with the error message:
**_Success!
The person in the picture is No connection adapters were found for '192.168.0.15:90/v1/vision/face/recognize'_**
![kép](https://user-images.githubusercontent.com/60293567/120173908-d2f71d00-c204-11eb-86d8-b3f5017b85d9.png)

**Comment by DivanX10** [comment]
Watch the [video](https://youtu.be/74b2bQDn1xA) how to properly configure deepstack, maybe this will help you

**Comment by t0mer** [comment]
I just pulled the lat version and i's working.
Maybe somthing in ypur configuration is wrong?
