### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_restful'

### ISSUE THREAD

**Issue by SmartLiving-Rocks** [t0mer/deepstack-trainer#5]
Hello, wonderful work! I also want to be part of it. The container does not start and the log file says: 

`Traceback (most recent call last):
  File "/opt/trainer/trainer.py", line 3, in <module>
    from flask_restful import Resource, Api
ModuleNotFoundError: No module named 'flask_restful'`

I have set all necessary parameter like DEEPSTACK_HOST_ADDRESS etc. Do I have to install flask_restful manually or do I have to do something else?

**Comment by t0mer** [comment]
Fixed it,
pull the new version.

**Comment by t0mer** [comment]
I just pulled the lat version and i's working.
Maybe somthing in ypur configuration is wrong?

**Comment by SmartLiving-Rocks** [comment]
> Fixed it,
> pull the new version.

Yes, you are the man! Thanks for the quick fix and have a nice weekend!
