### ISSUE TITLE
Allow Deepstack on other port?

### ISSUE THREAD

**Issue by cmille34** [t0mer/deepstack-trainer#6]
In your documentation/example you show that port 80 needs to be accessible and forwarded to port 5000 of the Deepstack instance.  I have port 80 tied to a different container, unfortunately, can I specify port 5000 for the deepstack instance somehow?

**Comment by t0mer** [comment]
Hi,
This is just an example, you can change the port fro 80 to whatever  you like.
I'm using port 5003 for the trainer and 5002 for deepstack.

**Comment by cmille34** [comment]
@t0mer I currently have my Deepstack running on port 5000 externally. How do I tell your deepstack-trainer to use port 5000? Do I simply add :5000 to the DEEPSTACK_HOST_ADDRESS parameter in the docker config?  When I do that I still get this error when trying to recognize a photo.

"Success!  -- The person in the picture is No connection adapters were found for '192.168.1.104:5000/v1/vision/face/recognize'

https://i.imgur.com/1IpgWzX.png
